# The contents of this file will eventually be appended to supabase/config.toml 
# once you run `supabase link` to connect to your Supabase project

[api]
enabled = true
port = 54321
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
